"""major update v3

Revision ID: 0a69092640c4
Revises: 
Create Date: 2021-01-25 21:15:40.462648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a69092640c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ikone',
    sa.Column('id_ikone', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ikona_path', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_ikone')
    )
    op.create_table('uporabniki',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('uporabnisko_ime', sa.String(length=50), nullable=False),
    sa.Column('e_naslov', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('registriral_cas', sa.DateTime(), nullable=False),
    sa.Column('potrjen', sa.Boolean(), nullable=False),
    sa.Column('potrjen_cas', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('uporabniki', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_uporabniki_e_naslov'), ['e_naslov'], unique=True)
        batch_op.create_index(batch_op.f('ix_uporabniki_uporabnisko_ime'), ['uporabnisko_ime'], unique=True)

    op.create_table('kategorije',
    sa.Column('id_kategorije', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ime_kategorije', sa.String(length=50), nullable=False),
    sa.Column('id_uporabnika', sa.INTEGER(), nullable=True),
    sa.Column('id_slike', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_uporabnika'], ['uporabniki.id'], ),
    sa.PrimaryKeyConstraint('id_kategorije')
    )
    with op.batch_alter_table('kategorije', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kategorije_id_slike'), ['id_slike'], unique=False)
        batch_op.create_index(batch_op.f('ix_kategorije_ime_kategorije'), ['ime_kategorije'], unique=False)

    op.create_table('vrednosti',
    sa.Column('id_vrednosti', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('naziv', sa.String(length=50), nullable=False),
    sa.Column('vrednost', sa.String(length=50), nullable=False),
    sa.Column('priljubljen', sa.Boolean(), nullable=True),
    sa.Column('id_kategorije', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['id_kategorije'], ['kategorije.id_kategorije'], ),
    sa.PrimaryKeyConstraint('id_vrednosti')
    )
    with op.batch_alter_table('vrednosti', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vrednosti_naziv'), ['naziv'], unique=False)
        batch_op.create_index(batch_op.f('ix_vrednosti_vrednost'), ['vrednost'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vrednosti', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vrednosti_vrednost'))
        batch_op.drop_index(batch_op.f('ix_vrednosti_naziv'))

    op.drop_table('vrednosti')
    with op.batch_alter_table('kategorije', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kategorije_ime_kategorije'))
        batch_op.drop_index(batch_op.f('ix_kategorije_id_slike'))

    op.drop_table('kategorije')
    with op.batch_alter_table('uporabniki', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_uporabniki_uporabnisko_ime'))
        batch_op.drop_index(batch_op.f('ix_uporabniki_e_naslov'))

    op.drop_table('uporabniki')
    op.drop_table('ikone')
    # ### end Alembic commands ###
