"""empty message

Revision ID: 79ee8d13fc71
Revises: 8834ef320adf
Create Date: 2022-02-15 22:35:25.710672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79ee8d13fc71'
down_revision = '8834ef320adf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=False)

    op.create_table('categories',
    sa.Column('category_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('category_name', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('category_id')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_category_name'), ['category_name'], unique=False)

    op.create_table('values',
    sa.Column('value_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('value', sa.String(length=50), nullable=True),
    sa.Column('popular', sa.Boolean(), nullable=True),
    sa.Column('category_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], ),
    sa.PrimaryKeyConstraint('value_id')
    )
    with op.batch_alter_table('values', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_values_popular'), ['popular'], unique=False)
        batch_op.create_index(batch_op.f('ix_values_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_values_value'), ['value'], unique=False)

    with op.batch_alter_table('vrednosti', schema=None) as batch_op:
        batch_op.drop_index('ix_vrednosti_naziv')
        batch_op.drop_index('ix_vrednosti_priljubljeno')
        batch_op.drop_index('ix_vrednosti_vrednost')

    op.drop_table('vrednosti')
    with op.batch_alter_table('uporabniki', schema=None) as batch_op:
        batch_op.drop_index('ix_uporabniki_e_naslov')
        batch_op.drop_index('ix_uporabniki_uporabnisko_ime')

    op.drop_table('uporabniki')
    with op.batch_alter_table('kategorije', schema=None) as batch_op:
        batch_op.drop_index('ix_kategorije_ime_kategorije')

    op.drop_table('kategorije')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kategorije',
    sa.Column('id_kategorije', sa.INTEGER(), nullable=False),
    sa.Column('ime_kategorije', sa.VARCHAR(length=50), nullable=True),
    sa.Column('id_uporabnika', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['id_uporabnika'], ['uporabniki.id'], ),
    sa.PrimaryKeyConstraint('id_kategorije')
    )
    with op.batch_alter_table('kategorije', schema=None) as batch_op:
        batch_op.create_index('ix_kategorije_ime_kategorije', ['ime_kategorije'], unique=False)

    op.create_table('uporabniki',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('uporabnisko_ime', sa.VARCHAR(length=50), nullable=False),
    sa.Column('e_naslov', sa.VARCHAR(length=100), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('uporabniki', schema=None) as batch_op:
        batch_op.create_index('ix_uporabniki_uporabnisko_ime', ['uporabnisko_ime'], unique=False)
        batch_op.create_index('ix_uporabniki_e_naslov', ['e_naslov'], unique=False)

    op.create_table('vrednosti',
    sa.Column('id_vrednosti', sa.INTEGER(), nullable=False),
    sa.Column('naziv', sa.VARCHAR(length=50), nullable=True),
    sa.Column('vrednost', sa.VARCHAR(length=50), nullable=True),
    sa.Column('id_kategorije', sa.INTEGER(), nullable=True),
    sa.Column('priljubljeno', sa.BOOLEAN(), nullable=True),
    sa.CheckConstraint('priljubljeno IN (0, 1)'),
    sa.CheckConstraint('priljubljeno IN (0, 1)'),
    sa.ForeignKeyConstraint(['id_kategorije'], ['kategorije.id_kategorije'], ),
    sa.PrimaryKeyConstraint('id_vrednosti')
    )
    with op.batch_alter_table('vrednosti', schema=None) as batch_op:
        batch_op.create_index('ix_vrednosti_vrednost', ['vrednost'], unique=False)
        batch_op.create_index('ix_vrednosti_priljubljeno', ['priljubljeno'], unique=False)
        batch_op.create_index('ix_vrednosti_naziv', ['naziv'], unique=False)

    with op.batch_alter_table('values', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_values_value'))
        batch_op.drop_index(batch_op.f('ix_values_title'))
        batch_op.drop_index(batch_op.f('ix_values_popular'))

    op.drop_table('values')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_category_name'))

    op.drop_table('categories')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
