"""empty message

Revision ID: 8834ef320adf
Revises: fd143339f58a
Create Date: 2021-03-30 18:49:59.522247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8834ef320adf'
down_revision = 'fd143339f58a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vrednosti', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priljubljeno', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_vrednosti_priljubljeno'), ['priljubljeno'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vrednosti', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vrednosti_priljubljeno'))
        batch_op.drop_column('priljubljeno')

    # ### end Alembic commands ###
